name: Python Code Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir pylint bandit
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r benchmark/requirements.txt

      - name: Run Pylint
        run: |
          PYTHONPATH=. pylint $(find . -name "*.py" | xargs)

      - name: Run Bandit
        run: |
          bandit -r . --exit-zero