name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from version.py
        id: get_version
        run: |
          VERSION=$(python -c "from utils.version import __version__; print(__version__)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Docker tag version: $VERSION"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/pyproxy:${{ env.VERSION }} -t ghcr.io/${{ github.repository_owner }}/pyproxy:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pyproxy:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/pyproxy:latest
