name: Build and Push Docker Image

on:
  workflow_run:
    workflows:
      - "Pylint Check"
      - "Run Unit Tests"
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from version.py
        id: get_version
        run: |
          VERSION=$(python -c "from pyproxy.utils.version import __version__; print(__version__)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Docker tag version: $VERSION"

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - id: docker_meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: |
            ghcr.io/${{ env.REPO_OWNER }}/pyproxy:${{ env.VERSION }}-slim
            ghcr.io/${{ env.REPO_OWNER }}/pyproxy:latest-slim
            ghcr.io/${{ env.REPO_OWNER }}/pyproxy:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_OWNER }}/pyproxy:latest
          tags: type=sha,format=long

      - name: Build and Push Docker images
        uses: docker/build-push-action@v6.14.0
        id: build-and-push
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Sign the publisehd Docker image
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}